name: "MooCrypt"

web: "[mootools.net/forge/p/MooCrypt](http://mootools.net/forge/p/MooCrypt)"

description: "MooCrypt is a set of MooTools extensions that make hashing/encrypting strings and arrays a breeze."

authors:
  - "[Christopher Pitt](http://mootools.net/forge/profile/sixtyseconds)"
  - "[Xunnamius](http://mootools.net/forge/profile/Xunnamius)"

license: "MIT License"

copyright: "&copy; 2010, Christopher Pitt + Enrique Erne + Xunnamius"

sources:
  - "Source/Array.Hex.js"
  - "Source/Array.RMD160.js"
  - "Source/Array.SHA-256.js"
  - "Source/Array.SHA-512.js"
  - "Source/String.Base64.js"
  - "Source/String.Common.js"
  - "Source/String.CRC-32.js"
  - "Source/String.Hex.js"
  - "Source/String.MD5.js"
  - "Source/String.RMD160.js"
  - "Source/String.SHA-1.js"
  - "Source/String.SHA-256.js"
  - "Source/String.SHA-512.js"
  - "Source/String.UTF-8.js"

# Values for MooTools forge

author: Xunnamius

current: 0.3.0

docs: http://github.com/Xunnamius/MooCrypt/blob/master/README.md

category: Native

tags: [string, array, encode, decode, encrypt, hash, hashing, SHA, SHA1, SHA256, SHA512, base64, CRC, MD5, RMD160, hex]
